---
- lineinfile: dest=/etc/yum/pluginconf.d/fastestmirror.conf regexp=^enabled= line=enabled=0
- yum: name=http://rdoproject.org/repos/openstack-kilo/rdo-testing-kilo.rpm state=present
- yum: name=* state=latest
- yum: name=openstack-selinux state=present
- copy: src=files/id_rsa dest=/home/vagrant/.ssh/id_packstack mode=0600 owner=vagrant group=vagrant
- copy: src=files/id_rsa.pub dest=/home/vagrant/.ssh/id_packstack.pub mode=0600 owner=vagrant group=vagrant
- copy: src=files/selinux dest=/etc/selinux/config mode=0644 owner=root group=root
- file: path=/home/vagrant/scripts state=directory owner=vagrant group=vagrant mode=0755
- shell: cat /home/vagrant/.ssh/id_packstack.pub >> /home/vagrant/.ssh/authorized_keys
- file: path=/home/vagrant/.ssh/authorized_keys owner=vagrant group=vagrant
- copy: src=files/motd dest=/etc/motd owner=root group=root mode=0644
- template: src=files/hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
